### ISSUE TITLE
Is this project still under development?

### ISSUE THREAD

**Issue by joshua19881228** [mustafamerttunali/deep-learning-training-gui#17]
Just curious about whether there is any further plan for this project, because it is really a good idea

**Comment by mustafamerttunali** [comment]
Firstly, thank you for interest,

Yes, I have started to develop version 2 of the app with using advanced code baseline and frameworks such as React, PyTorch, Docker, WebSocket, MaterialUI and more. Shortly, better code and visual design approach than first version.

**Comment by joshua19881228** [comment]
Wow, it's very exciting to hear about the plan! Looking forward to version 2 ~~
